[schwab] add tests for new action types
jbms/beancount-import pull request #125
Opened 2021-09-19 04:20 UTC by carljm

Follow up from #120, replaces #124

2021-09-20 01:24 UTC, Zburatorul requested changes
There are these two places where we should be able to identify the right account to use based on the meta keys. I missed that in the original PR somehow.
If we leave the FIXME, b-i should learn the right account over time, but seems like a simple fix.

2021-09-20 01:24 UTC, Zburatorul commented on testdata/source/schwab_csv/test_basic/import_results.beancount
> +  Expenses:FIXME                     -0.02 USD
This should be the `interest_income_account`

2021-09-20 01:24 UTC, Zburatorul commented on testdata/source/schwab_csv/test_basic/import_results.beancount
> +  Expenses:FIXME          -3.00 USD
This should be the `fees_account`.

2021-09-26 20:46 UTC, carljm commented
@Zburatorul Great catch! Fixed these, as well as a couple other misc things I noticed.

2021-09-26 21:06 UTC, carljm commented
Build breakage here is from breakage in main branch; fixed separately in #127

2021-09-27 00:17 UTC, Zburatorul reviewed
Looks good overall. I am unclear about whether the `features` arrays in the test output files should always be non-empty?

2021-09-27 00:17 UTC, Zburatorul commented on testdata/source/schwab_csv/test_basic/import_results.beancount
> +  Income:Interest:Schwab                0.05 USD
I can see that the right account is filled in here, but it's strange that the features array is now empty. Is this a regression?

2021-09-27 00:17 UTC, Zburatorul commented on testdata/source/schwab_csv/test_basic/import_results.beancount
> +; features: []
Should `features` be empty?

2021-09-27 00:19 UTC, carljm commented
I believe it is expected for features to be empty if there is no fixme posting in the txn. Features are used for the Bayesian prediction of fixme accounts.

2021-09-27 00:37 UTC, Zburatorul commented
> I believe it is expected for features to be empty if there is no fixme posting in the txn. Features are used for the Bayesian prediction of fixme accounts.

I see. In that case it's good to merge. Thank you.

2021-09-27 14:23 UTC, merged